// Generated by data/scripts/seed_dev_profiles.py — do not edit manually.

export interface DevProfile {
  label: string;
  deviceId: string;
  listId: string | null;
  description: string;
  swipeSummary: string;
}

export const DEV_PROFILES: DevProfile[] = [
  {
    label: "Cold Start",
    deviceId: "dev-cold-start",
    listId: "bb9c56d2-fa2c-4428-8871-00a30b18ee8a",
    description: "No swipe history",
    swipeSummary: "0 swipes",
  },
  {
    label: "Light User",
    deviceId: "dev-light",
    listId: "5d7195ef-3f9d-4fc2-80c0-aede4a46dfd1",
    description: "5 F likes — single taste vector",
    swipeSummary: "5 swipes",
  },
  {
    label: "Classic",
    deviceId: "dev-classic",
    listId: "c4a1a2e9-cc5e-44d2-91d8-5eb2b5d4064b",
    description: "Vintage/traditional taste, 2 modern off-persona per sex",
    swipeSummary: "10 likes + 5 passes × 2 sexes",
  },
  {
    label: "Modern",
    deviceId: "dev-modern",
    listId: "7c454b12-03d5-4d04-9009-ad5c2c841d91",
    description: "Trendy/nature taste, 2 vintage off-persona per sex",
    swipeSummary: "10 likes + 5 passes × 2 sexes",
  },
  {
    label: "Unique",
    deviceId: "dev-unique",
    listId: "55643ccc-0411-4856-b027-bc85551c97cd",
    description: "Rare/literary taste, 1 common name off-persona per sex",
    swipeSummary: "10 likes + 5 passes × 2 sexes",
  },
  {
    label: "Mixed",
    deviceId: "dev-mixed",
    listId: "d00ee1f4-9019-4a7b-9698-a96fe0b25637",
    description: "Classic + modern split — exercises k-means k=2 path",
    swipeSummary: "10 likes + 5 passes × 2 sexes",
  },
];
